config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'application#destroy'
  get    '/signup',  to: 'owners#new'
  resources :aliens
  resources :owners
  resources :toys, only: [:index]
  resources :planets, only: [:index, :show]
  resources :personalities, only: [:index, :show]
end

app/models/alien.rb
class Alien < ApplicationRecord
  belongs_to :planet
  belongs_to :owner
  belongs_to :toy
  has_many :personality_traits
  has_many :personalities, through: :personality_traits

  validates :name, presence: true, uniqueness: true
  validates :bio, length: { maximum: 250}
  validates :owner, presence: true, allow_nil: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_secure_password
  belongs_to :planet
  has_many :aliens

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :bio, length: { maximum: 250}
  # validates :owner, presence: true, allow_nil: true
end

app/models/personality.rb
class Personality < ApplicationRecord
  has_many :personality_traits
  has_many :aliens, through: :personality_traits
end

app/models/personality_trait.rb
class PersonalityTrait < ApplicationRecord
  belongs_to :personality
  belongs_to :alien
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :aliens
  has_many :owners
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many :aliens
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController

  def index
    @aliens = Alien.all
  end

  def show
    @alien = Alien.find(params[:id])
  end

  def update
    @alien = Alien.find(params[:id])
    if @alien.owner_id == session[:owner_id]
      @alien.update_column(:owner_id, nil)
      redirect_to "/owners/#{session[:owner_id]}"
    else
      @alien.update(owner_id: session[:owner_id])
      @alien.owner_id = session[:owner_id]
      redirect_to "/owners/#{session[:owner_id]}"
    end
  end

  def new
    @alien = Alien.new
  end

  def create
    @alien = Alien.new(aliens_params)
    if @alien.valid?
      @alien.save
      redirect_to alien_path(@alien)
    else
      flash[:errors] = @alien.errors.full_messages
      redirect_to new_alien_path
    end
  end

  private

  def aliens_params
    params.require(:alien).permit(:name, :bio, :planet_id, :toy_id, :owner_id, :therapy)
  end

  def update_params
    params.require(:alien).permit(:owner_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def redirect_if_not_logged_in 
    if !session[:owner_id]
      redirect_to login_path
    end
  end

  def current_owner
    Owner.find(session[:owner_id])
  end

  def destroy
    session[:owner_id] = nil
    redirect_to login_path
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
# before_action :redirect_if_not_logged_in


  def index
    @owners = Owner.all
  end

  def show
    if Owner.find_by_id(params[:id].to_s) == nil
      redirect_to login_path
    else
      @owner = Owner.find(params[:id])
      if session[:owner_id] == params[:id].to_i
        @current_owner = current_owner
      end
    end
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owners_params)
    if @owner.valid?
      @owner.save
      session[:owner_id] = @owner.id
      redirect_to owner_path(@owner)
    else
      flash[:errors] = @owner.errors.full_messages
      redirect_to new_owner_path
    end
  end


private

  def owners_params
    params.require(:owner).permit(:name, :bio, :planet_id, :email, :therapy, :password, :password_confirmation)
  end
end

app/controllers/personalities_controller.rb
class PersonalitiesController < ApplicationController
  def index
    @personalities = Personality.all
  end
  
  def show
    @personality = Personality.find(params[:id])
  end

end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @owner = Owner.find_by(email: params[:email])
    if @owner && @owner.authenticate(params[:password])
      session[:owner_id] = @owner.id
      redirect_to @owner
    else
      flash[:error] = 'Oops! That info doesn\'t look correct.'
      redirect_to login_path
    end
  end

end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end
  
  def show
    @toy = Toy.find(params[:id])
  end

end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/personalities_helper.rb
module PersonalitiesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/aliens/edit.html.erb
<h1>Change Alien's Favorite Toy</h1>

<h2>You are editing: <%= @alien.name %></h2>

<%= form_with model: @alien do |form| %>
  <p><%= form.label :toy%>
  <%= form.collection_select :toy_id, Toy.all, :id, :name%></p>

  <%= form.label "Is this a certified therapy alien?"%>
  <p><%= label :therapy, "Yes", value: true %>
  <%= form.radio_button :therapy, true, value: true%>
  <%= label :therapy, "No", value: true %>
  <%= form.radio_button :therapy, false, value: false%></p>
  
  <p><%= form.submit %></p>
<% end %>

app/views/aliens/index.html.erb
<h1>🛸 Alien Adoption Portal</h1>

<div class="form">
  <div class="alien-carousel">
    <%@aliens.each do |alien|%>
      <div class="alien-parent">
        <a href="/aliens/<%=alien.id%>"><img class="alien-picture" src="/assets/<%=alien.name%>.png" alt="<%=alien.name%>"/></a>
        <%if alien.owner_id %>
          <div class="alien-name owned"><%= link_to alien.name, alien_path(alien)%></div>
        <%else%>
          <div class="alien-name"><%= link_to alien.name, alien_path(alien)%></div>
        <%end%>
      </div>
    <%end%>
  </div>
</div>

app/views/aliens/new.html.erb
<h1>New Alien Form</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |m| %>
    <h3 style="color: red"><%= m %></h3>
  <% end %>
<% end %>


<%= form_with model: @alien do |form| %>
  <p><strong><%= form.label :name%></strong></p>
  <p><%= form.text_field :name %></p>

  <p><strong><%= form.label :bio%></strong></p>
  <p><%= form.text_area :bio%></p>

  <strong><%= form.label "Is this a certified therapy alien?"%></strong>
  <p><%= label :therapy, "Yes", value: true %>
  <%= form.radio_button :therapy, true, value: true%>
  <%= label :therapy, "No", value: true %>
  <%= form.radio_button :therapy, false, value: false%></p>

  <p><strong><%= form.label "Favorite Toy"%> </strong><%= form.collection_select :toy_id, Toy.all, :id, :name%></p>

  <p><strong><%= form.label "Planet of Origin"%> <strong><%= form.collection_select :planet_id, Planet.all, :id, :name %></p>

  <p><strong><%= form.label :owner%> <strong><%= form.collection_select :owner_id, Owner.all, :id, :name %></p>

  <p><%= form.submit %></p>
<% end %>

app/views/aliens/show.html.erb
<body class="alien-show-body">
  <h1>👋 Meet <%=@alien.name.titleize%>!</h1>
  <div><img class="alien-picture" src="/assets/<%=@alien.name%>.png" alt="<%=@alien.name%>"/></div>

  <% if @alien.owner == nil %>
    <p style="color: orange; font-style: oblique">Alien has no owners yet!</p>
  <%else%>
    <p>Owner: <%= link_to @alien.owner.name.titleize, owner_path(@alien.owner.id)%></p>
  <%end%>
  <div class="form">
    <p><strong>Bio: </strong><%=@alien.bio%></p>
    <p><strong>Therapy Alien? </strong><%=@alien.therapy%></p>
    <p><strong>Favorite Toy - </strong><%= @alien.toy.name %></p>
    <p><strong>Planet of Origin - </strong><a href='/planets/<%=@alien.planet.id%>'><%=@alien.planet.name%></a>


    <p><strong>Diet - </strong><%=@alien.planet.diet%></p>
    <p><strong>Personality Traits:</strong></p>
      <%@alien.personalities.each do |personality| %>
      <li><%=personality.name%></li>
      <%end%>
  </div>
  <br>
  <br>
  <% if @alien.owner_id == nil && session[:owner_id] == nil%>
    <%= form_with url: "/login" do |f| %>
    <%= f.submit "💾 Login to Adopt 💾", class: "button login_button"%>
    <% end %>
    <br>
    <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>

  <% elsif @alien.owner_id && session[:owner_id] == nil %>
    <button class="button" type="button" disabled>This Alien Has Been Adopted</button>
    <br>
    <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>

  <% elsif @alien.owner_id == session[:owner_id] %>
    <%= form_with model: @alien do |f| %>
    <%= f.submit "😭 Give Up Your Alien 😭", class: "button return_button"%>
    <% end %>
    <br>
    <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>

  <% elsif session[:owner_id] && @alien.owner_id == nil%>
    <%= form_with model: @alien do |f| %>
    <%= f.submit "😍 Adopt Me 😍", class: "button adopt_button" %>
    <% end %>
    <br>
    <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>

  <% else %>
    <button class="button" type="button" disabled>This Alien Has Been Adopted</button>
    <br>
    <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>
  <% end %>
</body>

app/views/owners/index.html.erb
<h1>Onwers</h1>

<ul>
<%@owners.each do |owner|%>
<li><%= link_to owner.name, owner_path(owner)%></li>
<%end%>
</ul>

app/views/owners/new.html.erb
<h1>Alien Adoption Sign Up</h1>
<span style="font-style: oblique">Make Your Profile Below:</span>

<% if flash[:errors] %>
  <br>
  <% flash[:errors].each do |m| %>
    <span style="color: red; font-style: oblique"><%= m %></span>
  <% end %>
<% end %>

<br>

<div class="form">
  <%= form_with model: @owner do |form| %>
    <p><strong><%= form.label :name%></strong> <%= form.text_field :name %></p>
    <p><strong><%= form.label :email%></strong> <%= form.text_field :email %></p>
    <p><strong><%= form.label :password%></strong> <%= form.password_field :password %></p>
    <p><strong><%= form.label "Retype Password"%></strong> <%= form.password_field :password_confirmation %></p>

    <hr>
    <p><strong><%= form.label :planet%></strong></p>
    <p><%= form.collection_select :planet_id, Planet.all, :id, :name %></p>

    <p><strong><%= form.label "Write A Little About Yourself:"%></strong></p>
    <p><%= form.text_area :bio%></p>

    <strong><%= form.label "Do you need a certified therapy alien?"%></strong>
    <p><%= label :therapy, "Yes", value: true %>
    <%= form.radio_button :therapy, true, value: true%>
    <%= label :therapy, "No", value: true %>
    <%= form.radio_button :therapy, false, value: false%></p>

    <p><%= form.submit %></p>
  <% end %>
<div>

app/views/owners/show.html.erb
<% if @current_owner %>

<body class="owner-show-body">
  <h1>🖖 Hey, <%=@owner.name.titleize%>!</h1>
  <div class="form">
    <p><strong>Bio:</strong> <%=@owner.bio%></p>
    <p><strong>Planet:</strong> <%=link_to @owner.planet.name, planet_path(@owner.planet.id)%></p>
    <p><strong>Therapy?</strong> <%=@owner.therapy%></p>
    <p><strong>Email:</strong> <%=@owner.email%></p>
    <p><strong>Aliens you've adopted:</strong></p>
    <% if @owner.aliens == nil || @owner.aliens == [] %>
      <span style="font-style: oblique">You haven't adopted any aliens yet!</span>
      <br/>
    <% else %>
    <ul>
      <%@owner.aliens.each do |alien| %>
        <li><%= link_to alien.name, alien_path(alien)%></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <br>
  <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>
  <br>
  <%= button_to "✌️ I Wanna Loggity Log Out ✌️", logout_path, method: :delete, class: "button logout_button"%>

<% elsif session[:owner_id] == nil %>

  <h1>Sorry, this profile is private.</h1>
  <h3>Please choose an option: </h3>
  <%= button_to "See All Available Aliens", '/aliens', method: :get, class: "button all_button"%>
  <br>
  <form action="/login">
      <input type="submit" value="Login" class="button login_button"/>
  </form>

 <% else %>
 <h1>Sorry, this profile is private.</h1>
  <h3>Please choose an option: </h3>
  <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>
  <br>
  <form action="/owners/<%= session[:owner_id]%>">
      <input type="submit" value="Go to My Profile" class="button login_button"/>
  </form>

<% end %>
</body>

app/views/personalities/index.html.erb
<h1>Personalities</h1>

<ul>
<%@personalities.each do |personality|%>
<li><%= personality.name%></li>
<%end%>
</ul>

app/views/personalities/show.html.erb
<h1>Personalities#show</h1>
<p>Find me in app/views/personalities/show.html.erb</p>

app/views/planets/index.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


<h1>🚀 Planets</h1>

<br>
<div class="form">
  <div class="alien-carousel">
    <%@planets.each do |planet|%>
      <div class="alien-parent">
        <a href="/planets/<%=planet.id%>"><img class="alien-picture" src="/assets/<%=planet.name%>.jpg" alt="<%=planet.name%>"/></a>
        <div class="alien-name"><%= link_to planet.name, planet_path(planet)%></div>
      </div>
    <%end%>
  </div>
</div>

app/views/planets/show.html.erb
<body class="planet-show-body">
  <%if session[:owner_id] %>
    <h1>🌐 <%=@planet.name%></h1>
    <div><img class="alien-picture" src="/assets/<%=@planet.name%>.jpg" alt="<%=@planet.name%>"/></div>
    <div class="form">
      <p><strong>The climate on <%= @planet.name %> is - </strong><%=@planet.climate%></p>
      <p><strong>Life forms on <%= @planet.name %> eat - </strong><%=@planet.diet%></p>
      <p><strong>Fellow aliens who call <%= @planet.name %> home:</strong></p>
      <ul>
        <%@planet.aliens.each do |alien|%>
          <li><a href='/aliens/<%=alien.id%>'><%=alien.name%></a></li>
        <%end%>
      </ul>
    </div>
    <br>
    <%= button_to "🌎 See All Planets 🌍", '/planets', method: :get, class: "button adopt_button"%>
    <br>
    <%= button_to "👽 See All Available Aliens 👽", '/aliens', method: :get, class: "button all_button"%>
  <%else%>
    <h1>🌏 Please login to view planet details.</h1>
    <h3>Please choose an option:</h3>
    <%= button_to "See All Available Aliens", '/aliens', method: :get, class: "button all_button"%>
    <br>
    <form action="/login">
        <input type="submit" value="Login" class="button login_button"/>
    </form>
  <%end%>
</body>

app/views/toys/index.html.erb
<h1>Toys</h1>

<ul>
<%@toys.each do |toy|%>
<li><%= toy.name %></li>
<%end%>
</ul>