config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'application#destroy'
  get    '/signup',  to: 'owners#new'
  resources :aliens
  resources :owners
  resources :toys, only: [:index]
  resources :planets, only: [:index, :show]
  resources :personalities, only: [:index, :show]
end

app/models/alien.rb
class Alien < ApplicationRecord
  belongs_to :planet
  belongs_to :owner
  belongs_to :toy
  has_many :personality_traits
  has_many :personalities, through: :personality_traits

  validates :name, presence: true, uniqueness: true
  validates :bio, length: { maximum: 250}
  validates :owner, presence: true, allow_nil: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_secure_password
  belongs_to :planet
  has_many :aliens

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :bio, length: { maximum: 250}
  # validates :owner, presence: true, allow_nil: true
end

app/models/personality.rb
class Personality < ApplicationRecord
  has_many :personality_traits
  has_many :aliens, through: :personality_traits
end

app/models/personality_trait.rb
class PersonalityTrait < ApplicationRecord
  belongs_to :personality
  belongs_to :alien
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :aliens
  has_many :owners
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many :aliens
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController

  def index
    @aliens = Alien.all
  end

  def show
    @alien = Alien.find(params[:id])
  end

  def update
    @alien = Alien.find(params[:id])
    if @alien.owner_id == session[:owner_id]
      @alien.update_column(:owner_id, nil)
      redirect_to "/owners/#{session[:owner_id]}"
    else
      @alien.update(owner_id: session[:owner_id])
      @alien.owner_id = session[:owner_id]
      redirect_to "/owners/#{session[:owner_id]}"
    end
  end

  def new
    @alien = Alien.new
  end

  def create
    @alien = Alien.new(aliens_params)
    if @alien.valid?
      @alien.save
      redirect_to alien_path(@alien)
    else
      flash[:errors] = @alien.errors.full_messages
      redirect_to new_alien_path
    end
  end

  private

  def aliens_params
    params.require(:alien).permit(:name, :bio, :planet_id, :toy_id, :owner_id, :therapy)
  end

  def update_params
    params.require(:alien).permit(:owner_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def redirect_if_not_logged_in 
    if !session[:owner_id]
      redirect_to login_path
    end
  end

  def current_owner
    Owner.find(session[:owner_id])
  end

  def destroy
    session[:owner_id] = nil
    redirect_to login_path
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
# before_action :redirect_if_not_logged_in


  def index
    @owners = Owner.all
  end

  def show
    if Owner.find_by_id(params[:id].to_s) == nil
      redirect_to login_path
    else
      @owner = Owner.find(params[:id])
      if session[:owner_id] == params[:id].to_i
        @current_owner = current_owner
      end
    end
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owners_params)
    if @owner.valid?
      @owner.save
      session[:owner_id] = @owner.id
      redirect_to owner_path(@owner)
    else
      flash[:errors] = @owner.errors.full_messages
      redirect_to new_owner_path
    end
  end


private

  def owners_params
    params.require(:owner).permit(:name, :bio, :planet_id, :email, :therapy, :password, :password_confirmation)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @owner = Owner.find_by(email: params[:email])
    if @owner && @owner.authenticate(params[:password])
      session[:owner_id] = @owner.id
      redirect_to @owner
    else
      flash[:error] = 'Oops! That info doesn\'t look correct.'
      redirect_to login_path
    end
  end

end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end
  
  def show
    @toy = Toy.find(params[:id])
  end

end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/personalities_helper.rb
module PersonalitiesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlienAdoptionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset='utf-8'>

    <link href="https://fonts.googleapis.com/css?family=Bai+Jamjuree:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">

      <div class="alien-logo">
        <% if session[:owner_id] %>
           <a href="<%=owner_path(session[:owner_id].to_s)%>"><p class="logo-nav">
             <!-- <img src="/assets/alien.png" alt="alien-adoption"> -->
             👽 Alien Adopt</p></a>
        <%else%>
          <a href="/login"><p class="logo-nav">
            <!-- <%= image_tag ("alien.png")%> -->
            👽 Alien Adopt</p></a>
        <%end%>
      </div>

      <div class="nav-links">
        <%if session[:owner_id] == nil%>
          <p><a href="/login">My Profile</a></p>
        <%else%>
          <p><a href="/owners/<%= session[:owner_id].to_s %>">My Profile</a></p>
        <%end%>
        <p><%= link_to "Home Planets", planets_path %></p>
        <p><%= link_to "Adopt An Alien", aliens_path %></p>
        <% if session[:owner_id] == nil%>
          <p><%= button_to "Login", '/login', class: "button login_button" %></p>
        <%else%>
            <p><%= button_to "Logout", '/logout', method: :delete, class: "button logout_button" %></p>
        <% end %>
      </div>
  </div>
    <%= yield %>
  <br>
  <br>
  </body>
</html>